### ISSUE TITLE
Problem with easy-thumbnails (and django-filer possible)

### ISSUE THREAD

**Issue by SalahAdDin** [shuup/shuup#1139]
I had other error with dependencies:
```bash
/manage.py runserver                             ✓  2866  22:55:30 
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f2f2e636a60>
Traceback (most recent call last):
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/utils/autoreload.py", line 250, in raise_last_exception
    six.reraise(*_exception)
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/easy_thumbnails/models.py", line 6, in <module>
    from easy_thumbnails import utils, signal_handlers
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/easy_thumbnails/utils.py", line 15, in <module>
    from easy_thumbnails.conf import settings
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/easy_thumbnails/conf.py", line 334, in <module>
    settings = Settings()
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/easy_thumbnails/conf.py", line 21, in __init__
    super(AppSettings, self).__init__(*args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'settings_module'

```

Searching about it i found this [issue](https://github.com/divio/django-filer/issues/977), i read the comments and i decided update this package but not `django-filer`.

I don't get this error anymore, but i get other.

I'm working with `1.9.13`, needed to `shuup`, so, this problem is not about only `django 1.11`.
